USE QLKHViettin;
SET NAMES utf8mb4;
SET SESSION time_zone = '+00:00';
START TRANSACTION;
INSERT INTO Customer (HoTen,Email) VALUES ('Nguyễn Thị Ánh 🌟','smoke@example.test');
SET @kh=LAST_INSERT_ID();
INSERT INTO `Role` (TenRole) VALUES ('Agent');
SET @role=LAST_INSERT_ID();
INSERT INTO UserAccount (MaRole,HoTen,Username,PasswordHash) VALUES (@role,'Nhân viên thử nghiệm','smoke-agent','test-only-not-a-real-password');
SET @agent=LAST_INSERT_ID();
INSERT INTO ChatSession (MaKH,MaAgent) VALUES (@kh,@agent);
SET @session=LAST_INSERT_ID();
INSERT INTO Message (MaSession,NguoiGui,NoiDung,DoTinCayAI) VALUES (@session,'Khách hàng','Tôi cần hỗ trợ thẻ',0.85);
SET @message=LAST_INSERT_ID();
INSERT INTO TicketCategory (TenCategory) VALUES ('Thẻ');
SET @category=LAST_INSERT_ID();
INSERT INTO Ticket (MaKH,MaSession,MaCategory,MaAgent,TieuDe,NoiDung) VALUES (@kh,@session,@category,@agent,'Hỗ trợ thẻ','Kiểm tra dữ liệu tiếng Việt');
SET @ticket=LAST_INSERT_ID();
INSERT INTO Handover (MaSession,MaAgent,LyDo) VALUES (@session,@agent,'Cần nhân viên hỗ trợ');
INSERT INTO SentimentAnalysis (MaMessage,CamXuc,DiemCamXuc) VALUES (@message,'Trung lập',0.5);
INSERT INTO AISuggestion (MaMessage,NoiDungGoiY,DoTinCay) VALUES (@message,'Xin chào',0.85);
INSERT INTO ConversationSummary (MaSession,NoiDungTomTat) VALUES (@session,'Khách hàng cần hỗ trợ thẻ');
INSERT INTO Evaluation (MaKH,MaTicket,SoSao,DiemNPS) VALUES (@kh,@ticket,5,9);
INSERT INTO KnowledgeBase (MaUser,TieuDe,NoiDung,TrangThai) VALUES (@agent,'Hướng dẫn thẻ','Nội dung thử nghiệm','Đã xuất bản');
SET @kb=LAST_INSERT_ID();
INSERT INTO KnowledgeChunk (MaKB,ThuTu,NoiDung,Embedding,TenMoHinh,SoChieu) VALUES (@kb,0,'Đoạn thử nghiệm',JSON_ARRAY(0.1,0.2,0.3),'test-model',3);
INSERT INTO AuditLog (MaUser,HanhDong,DoiTuong,MaDoiTuong) VALUES (@agent,'SMOKE_TEST','KnowledgeBase',@kb);
SELECT 'unicode' AS test, CAST(HoTen AS BINARY)=CAST('Nguyễn Thị Ánh 🌟' AS BINARY) AS passed FROM Customer WHERE MaKH=@kh;
SELECT 'json' AS test, JSON_LENGTH(Embedding)=SoChieu AS passed FROM KnowledgeChunk WHERE MaKB=@kb;
SELECT 'joined_ticket' AS test, COUNT(*)=1 AS passed FROM Ticket t JOIN Customer c ON t.MaKH=c.MaKH JOIN ChatSession s ON t.MaSession=s.MaSession WHERE t.MaTicket=@ticket;
SELECT 'table_count' AS test, COUNT(*)=15 AS passed FROM information_schema.tables WHERE table_schema=DATABASE();
SELECT 'storage' AS test, COUNT(*)=15 AS passed FROM information_schema.tables WHERE table_schema=DATABASE() AND engine='InnoDB' AND table_collation='utf8mb4_0900_ai_ci';
ROLLBACK;
