(() => {
 const en=document.documentElement.lang==='en',t=(vi,eng)=>en?eng:vi,$=id=>document.getElementById(id);
 let user,current=null,next=null,busy=false,indexed=false,configured=false,dirty=false;
 const keys=new Map(),labels={'Nháp':t('Nháp','Draft'),'Đã xuất bản':t('Đã xuất bản','Published'),'Lưu trữ':t('Ngừng sử dụng','Unpublished')};
 const errors={FORBIDDEN:t('Chức năng dành cho quản trị viên.','Administrator access required.'),KNOWLEDGE_CHANGED:t('Tài liệu đã thay đổi. Làm mới trước khi tiếp tục.','The document changed. Refresh before continuing.'),KNOWLEDGE_NOT_INDEXED:t('Hãy tạo dữ liệu tìm kiếm cho bản nháp hiện tại.','Prepare search data for the current draft first.'),AI_NOT_CONFIGURED:t('Khởi động backend với -EnableAI và nhập khóa API của nhà cung cấp đã chọn.','Start the backend with -EnableAI and enter your selected provider API key.'),KNOWLEDGE_READ_ONLY:t('Phiên bản này chỉ được xem. Hãy tạo phiên bản mới.','This version is read-only. Create a new version.'),AI_UNAVAILABLE:t('Dịch vụ AI chưa phản hồi. Kiểm tra khóa, kết nối hoặc thử lại.','AI service is unavailable. Check your key, connection or retry.'),AI_RATE_LIMITED:t('Dịch vụ AI đang giới hạn yêu cầu hoặc hạn mức. Vui lòng thử lại sau.','AI service rate or quota limit reached. Try again later.')};
 function notice(s,error=false){$('notice').textContent=s;$('notice').classList.toggle('error',error);}
 function node(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
 async function api(path,body){let storage,key;if(body!==undefined){const bytes=new TextEncoder().encode(JSON.stringify([user.id,path,body]));storage='vc-kb-'+[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');try{key=sessionStorage.getItem(storage);}catch{}key||=keys.get(storage)||crypto.randomUUID();keys.set(storage,key);try{sessionStorage.setItem(storage,key);}catch{}}
  const res=await fetch(path,{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(70000),...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Vietincare-Request':'1','Idempotency-Key':key},body:JSON.stringify(body)})});if(res.status===401){location.replace(`login-${en?'en':'vi'}.html`);throw Error('UNAUTHENTICATED');}const data=await res.json();if(storage&&(res.ok||res.status<500)){keys.delete(storage);try{sessionStorage.removeItem(storage);}catch{}}if(!res.ok)throw Error(data.error);return data;
 }
 function controls(){document.querySelectorAll('.page button,.page input,.page textarea').forEach(el=>el.disabled=busy);const draft=!current||current.status==='Nháp';$('saveKnowledge').hidden=!draft;$('knowledgeTitle').readOnly=!draft;$('knowledgeContent').readOnly=!draft;$('indexKnowledge').hidden=!current||!draft;$('indexKnowledge').disabled=busy||dirty||!configured;$('publishKnowledge').hidden=!current||!draft;$('publishKnowledge').disabled=busy||dirty||!indexed;$('archiveKnowledge').hidden=current?.status!=='Đã xuất bản';$('reviseKnowledge').hidden=current?.status!=='Đã xuất bản';$('previewForm').hidden=!current||!indexed;$('previewForm').querySelector('button').disabled=busy||dirty||!configured;$('dirtyNotice').textContent=dirty?t('Có thay đổi chưa lưu. Lưu bản nháp trước khi tạo dữ liệu tìm kiếm hoặc xuất bản.','Unsaved changes. Save the draft before preparing search data or publishing.'):'';}
 async function action(work){if(busy)return;busy=true;controls();notice(t('Đang xử lý…','Working…'));try{await work();}catch(e){notice(errors[e.message]||t('Chưa hoàn thành. Nội dung vẫn giữ trong biểu mẫu; thử lại hoặc làm mới.','Could not complete the action. Your form remains available; retry or refresh.'),true);}finally{busy=false;controls();}}
 function fresh(){current=null;indexed=false;dirty=false;$('knowledgeForm').reset();$('editor').hidden=false;$('editorTitle').textContent=t('Tài liệu mới','New document');$('documentState').textContent='';$('chunkStatus').textContent='';$('chunkDetails').hidden=true;$('previewAnswer').textContent='';$('language').hash='';history.replaceState(null,'',location.pathname);controls();}
 async function list(append=false){const data=await api('/api/knowledge'+(append&&next?`?before=${next}`:''));configured=data.aiConfigured;const provider=data.aiProvider==='gemini'?'Google Gemini':'OpenAI';$('keyStatus').textContent=configured?t(`${provider} đã được cấu hình. Nội dung dùng để tạo dữ liệu tìm kiếm và câu trả lời sẽ được gửi đến ${provider}.`,`${provider} is configured. Content used for search data and answers will be sent to ${provider}.`):t('AI chưa được cấu hình. Bạn vẫn có thể soạn và lưu bản nháp.','AI is not configured. You can still create and save drafts.');if(!append)$('documents').replaceChildren();for(const doc of data.documents){const li=node('li',''),a=node('a','');a.className='chat-link';a.href=`#${doc.id}`;a.dataset.id=doc.id;a.append(node('strong',doc.title),node('small',`KB-${doc.id} · ${labels[doc.status]||doc.status}`));li.append(a);$('documents').append(li);}next=data.next;$('moreDocuments').hidden=!next;$('listStatus').textContent=$('documents').children.length?'':t('Chưa có tài liệu.','No documents yet.');}
 async function detail(id){$('editor').hidden=true;const data=await api(`/api/knowledge/${id}`);current=data.document;indexed=data.indexed;configured=data.aiConfigured;dirty=false;$('editorTitle').textContent=`KB-${id}`;$('documentState').textContent=`${labels[current.status]||current.status} · ${t('Lần sửa','Edit')} ${current.version}${current.replacesId?` · ${t('Thay thế','Replaces')} KB-${current.replacesId}`:''}`;$('knowledgeTitle').value=current.title;$('knowledgeContent').value=current.content||'';$('chunkStatus').textContent=`${data.chunks.length} ${t('đoạn nguồn','source chunks')} · ${indexed?t('Đã tạo dữ liệu tìm kiếm','Search data prepared'):t('Chưa sẵn sàng tìm kiếm','Search data not ready')}`;$('chunkList').replaceChildren(...data.chunks.map(c=>node('p',`${c.position+1}. ${c.content}`)));$('chunkDetails').hidden=!data.chunks.length;$('previewAnswer').textContent='';$('editor').hidden=false;$('language').hash=id;history.replaceState(null,'',`#${id}`);document.querySelectorAll('#documents a').forEach(a=>a.setAttribute('aria-current',String(Number(a.dataset.id)===id)));controls();}
 $('knowledgeForm').addEventListener('input',()=>{dirty=true;controls();});
 $('knowledgeForm').addEventListener('submit',e=>{e.preventDefault();action(async()=>{const data=await api(current?`/api/knowledge/${current.id}/save`:'/api/knowledge',{title:$('knowledgeTitle').value.trim(),content:$('knowledgeContent').value.trim(),...(current?{version:current.version}:{})});current={id:data.id,title:$('knowledgeTitle').value.trim(),content:$('knowledgeContent').value.trim(),version:current?current.version+1:1,status:'Nháp'};dirty=false;notice(t('Đã lưu bản nháp.','Draft saved.'));await list();await detail(data.id);});});
 $('documents').addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();action(async()=>{await detail(Number(a.dataset.id));notice('');});});
 $('newDocument').addEventListener('click',()=>{if(!busy){fresh();notice('');}});
 $('refreshKnowledge').addEventListener('click',()=>action(async()=>{await list();if(current)await detail(current.id);else $('editor').hidden=false;notice('');}));
 $('moreDocuments').addEventListener('click',()=>action(async()=>{await list(true);notice('');}));
 for(const [button,operation] of [['indexKnowledge','index'],['publishKnowledge','publish'],['archiveKnowledge','archive']])$(button).addEventListener('click',()=>action(async()=>{await api(`/api/knowledge/${current.id}/${operation}`,{version:current.version});notice(t('Đã cập nhật tài liệu.','Document updated.'));await list();await detail(current.id);}));
 $('reviseKnowledge').addEventListener('click',()=>action(async()=>{const data=await api('/api/knowledge',{title:current.title,content:current.content,replacesId:current.id});await list();await detail(data.id);notice(t('Đã tạo bản nháp mới. Bản đã xuất bản vẫn được sử dụng cho đến khi bản mới được xuất bản.','New draft created. The published version stays active until this version is published.'));}));
 $('previewForm').addEventListener('submit',e=>{e.preventDefault();action(async()=>{const data=await api(`/api/knowledge/${current.id}/preview`,{version:current.version,question:$('previewQuestion').value,language:en?'en':'vi'});$('previewAnswer').textContent=data.answer&&data.sources.length?`${data.answer}\n\n${t('Nguồn','Sources')}: ${data.sources.map(s=>`${s.title} (#${s.id})`).join(', ')}`:t('Chưa có đủ nguồn phù hợp để trả lời.','No sufficient matching sources to answer.');notice(t('Kết quả thử, chưa gửi cho khách hàng.','Preview only; not sent to customers.'));});});
 (async()=>{try{user=await window.VietinWorkspace.ready;if(user.role!=='Admin')throw Error('FORBIDDEN');$('knowledgeWorkspace').hidden=false;const id=/^[1-9]\d{0,9}$/.test(location.hash.slice(1))?Number(location.hash.slice(1)):null;await action(async()=>{fresh();await list();if(id)await detail(id);notice('');});}catch(e){notice(errors[e.message]||t('Không tải được kho tri thức.','Unable to load knowledge base.'),true);}})();
})();
