-- MySQL 8.0.46. Run with npm run db:migrate (preflight, lock and step journal).
-- Existing rows are preserved. Customer links are NOT guessed from matching emails.
-- Each statement is one journaled step; do not add stored procedures here.
ALTER TABLE UserAccount ADD COLUMN EmailNormalized VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin GENERATED ALWAYS AS (LOWER(TRIM(Email))) STORED, ADD CONSTRAINT UQ_UserAccount_Email UNIQUE (EmailNormalized);
ALTER TABLE Customer ADD COLUMN MaUser INT NULL, ADD CONSTRAINT UQ_Customer_User UNIQUE (MaUser), ADD CONSTRAINT FK_Customer_User FOREIGN KEY (MaUser) REFERENCES UserAccount(MaUser);
INSERT INTO Role(TenRole, MoTa) VALUES ('Customer','Khách hàng'),('Agent','Nhân viên hỗ trợ'),('Supervisor','Quản lý hỗ trợ'),('Admin','Quản trị') ON DUPLICATE KEY UPDATE TenRole=Role.TenRole;
CREATE TABLE AuthSession (TokenHash BINARY(32) PRIMARY KEY, MaUser INT NOT NULL, CreatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), ExpiresAt DATETIME(3) NOT NULL, CONSTRAINT FK_AuthSession_User FOREIGN KEY(MaUser) REFERENCES UserAccount(MaUser), INDEX IX_AuthSession_Expiry(ExpiresAt), INDEX IX_AuthSession_User(MaUser)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE AuthThrottle (ThrottleKey BINARY(32) PRIMARY KEY, Attempts INT NOT NULL DEFAULT 0, WindowEnd DATETIME(3) NOT NULL, CHECK(Attempts >= 0), INDEX IX_AuthThrottle_Expiry(WindowEnd)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ALTER TABLE ChatSession ADD CONSTRAINT UQ_ChatSession_Customer UNIQUE(MaSession,MaKH), ADD CONSTRAINT CK_ChatSession_Time CHECK(ThoiGianKetThuc IS NULL OR (ThoiGianBatDau IS NOT NULL AND ThoiGianKetThuc >= ThoiGianBatDau));
ALTER TABLE Ticket ADD CONSTRAINT UQ_Ticket_Customer UNIQUE(MaTicket,MaKH), ADD CONSTRAINT FK_Ticket_SessionOwner FOREIGN KEY(MaSession,MaKH) REFERENCES ChatSession(MaSession,MaKH), ADD CONSTRAINT CK_Ticket_Status CHECK(TrangThai IS NOT NULL AND TrangThai IN ('Mới','Đang xử lý','Đã giải quyết','Đã đóng')), ADD CONSTRAINT CK_Ticket_Priority CHECK(MucDoUuTien IS NOT NULL AND MucDoUuTien IN ('Thấp','Trung bình','Cao','Khẩn cấp')), ADD CONSTRAINT CK_Ticket_Time CHECK(NgayTao IS NOT NULL AND (NgayCapNhat IS NULL OR NgayCapNhat >= NgayTao) AND (NgayDong IS NULL OR (NgayDong >= NgayTao AND TrangThai='Đã đóng'))), ADD INDEX IX_Ticket_CustomerDate(MaKH,NgayTao), ADD INDEX IX_Ticket_AgentStatus(MaAgent,TrangThai);
ALTER TABLE Evaluation ADD CONSTRAINT FK_Evaluation_SessionOwner FOREIGN KEY(MaSession,MaKH) REFERENCES ChatSession(MaSession,MaKH), ADD CONSTRAINT FK_Evaluation_TicketOwner FOREIGN KEY(MaTicket,MaKH) REFERENCES Ticket(MaTicket,MaKH), ADD CONSTRAINT CK_Evaluation_Target CHECK((MaSession IS NOT NULL) + (MaTicket IS NOT NULL) = 1), ADD CONSTRAINT CK_Evaluation_Stars CHECK(SoSao IS NOT NULL AND SoSao BETWEEN 1 AND 5), ADD CONSTRAINT CK_Evaluation_NPS CHECK(DiemNPS IS NULL OR DiemNPS BETWEEN 0 AND 10), ADD CONSTRAINT UQ_Evaluation_Session UNIQUE(MaSession), ADD CONSTRAINT UQ_Evaluation_Ticket UNIQUE(MaTicket);
ALTER TABLE Message ADD COLUMN MaUser INT NULL, ADD CONSTRAINT FK_Message_User FOREIGN KEY(MaUser) REFERENCES UserAccount(MaUser), ADD INDEX IX_Message_SessionTime(MaSession,ThoiGian), ADD CONSTRAINT CK_Message_Confidence CHECK(DoTinCayAI IS NULL OR DoTinCayAI BETWEEN 0 AND 100);
ALTER TABLE SentimentAnalysis ADD CONSTRAINT CK_Sentiment_Label CHECK(CamXuc IN ('Tích cực','Trung tính','Tiêu cực'));
CREATE TABLE TicketReply (MaReply INT AUTO_INCREMENT PRIMARY KEY, MaTicket INT NOT NULL, MaUser INT NOT NULL, NoiDung LONGTEXT NOT NULL, ThoiGian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), CONSTRAINT FK_Reply_Ticket FOREIGN KEY(MaTicket) REFERENCES Ticket(MaTicket), CONSTRAINT FK_Reply_User FOREIGN KEY(MaUser) REFERENCES UserAccount(MaUser), INDEX IX_Reply_TicketTime(MaTicket,ThoiGian)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE TicketStatusHistory (MaHistory INT AUTO_INCREMENT PRIMARY KEY, MaTicket INT NOT NULL, TrangThaiCu VARCHAR(30) NULL, TrangThaiMoi VARCHAR(30) NOT NULL, MaUser INT NOT NULL, ThoiGian DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), CONSTRAINT FK_History_Ticket FOREIGN KEY(MaTicket) REFERENCES Ticket(MaTicket), CONSTRAINT FK_History_User FOREIGN KEY(MaUser) REFERENCES UserAccount(MaUser), CHECK(TrangThaiCu IS NULL OR TrangThaiCu IN ('Mới','Đang xử lý','Đã giải quyết','Đã đóng')), CHECK(TrangThaiMoi IN ('Mới','Đang xử lý','Đã giải quyết','Đã đóng')), INDEX IX_History_TicketTime(MaTicket,ThoiGian)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE MessageSource (MaSource INT AUTO_INCREMENT PRIMARY KEY, MaMessage INT NOT NULL, MaChunk INT NOT NULL, TieuDeNguon VARCHAR(200) NOT NULL, NoiDungNguon LONGTEXT NOT NULL, SourceHash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, NgayTao DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), CONSTRAINT FK_Source_Message FOREIGN KEY(MaMessage) REFERENCES Message(MaMessage), CONSTRAINT FK_Source_Chunk FOREIGN KEY(MaChunk) REFERENCES KnowledgeChunk(MaChunk), CONSTRAINT UQ_MessageSource UNIQUE(MaMessage,MaChunk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE SystemSetting (SettingKey VARCHAR(100) PRIMARY KEY, SettingValue JSON NOT NULL, MaUser INT NULL, UpdatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), CONSTRAINT FK_Setting_User FOREIGN KEY(MaUser) REFERENCES UserAccount(MaUser)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ALTER TABLE Handover ADD COLUMN ThoiGianTiepNhan DATETIME(3) NULL, ADD COLUMN ThoiGianKetThuc DATETIME(3) NULL, ADD COLUMN ActiveSession INT GENERATED ALWAYS AS (CASE WHEN TrangThai IN ('Chờ tiếp nhận','Đã tiếp nhận') THEN MaSession ELSE NULL END) STORED, ADD CONSTRAINT UQ_Handover_Active UNIQUE(ActiveSession), ADD CONSTRAINT CK_Handover_Status CHECK(TrangThai IS NOT NULL AND TrangThai IN ('Chờ tiếp nhận','Đã tiếp nhận','Đã kết thúc','Đã hủy')), ADD CONSTRAINT CK_Handover_Time CHECK((ThoiGianTiepNhan IS NULL OR ThoiGianTiepNhan >= ThoiGian) AND (ThoiGianKetThuc IS NULL OR ThoiGianKetThuc >= COALESCE(ThoiGianTiepNhan,ThoiGian)));
